Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.cognitoUserPool}
      UsernameAttributes: 
        - email
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: |
        Welcome to DropBucket! 

        Please enter the verification code: {####}

        Note: Your account will be disabled until an administrator enables it.

        - The DropBucket Team
      EmailVerificationSubject: "Verify your DropBucket account"
      LambdaConfig:
        PostConfirmation: 
          "Fn::GetAtt":
            - DisableUserLambdaFunction
            - Arn
  CognitoUserPoolClient:  
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.stage}-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  UserPoolLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName: 
        "Fn::GetAtt":
          - DisableUserLambdaFunction
          - Arn
      SourceArn: "arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/*"

# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      "Ref": CognitoUserPool
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
