Resources:
  FileSharingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamoDbTableName}
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: filePath
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: filePath
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: 'ttl'
        Enabled: true
      SSESpecification:
        SSEEnabled: true

Outputs:
  FileSharingTableName:
    Value:
      Ref: FileSharingTable