Resources:
  FileSharingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamoDbTableName}
      AttributeDefinitions:
        - AttributeName: shareId
          AttributeType: S
        - AttributeName: to
          AttributeType: S
        - AttributeName: from
          AttributeType: S
        - AttributeName: filePath
          AttributeType: S
      KeySchema:
        - AttributeName: shareId
          KeyType: HASH
      GlobalSecondaryIndex:
        - IndexName: ${self:custom.dynamoDbTableToIdx}
          KeySchema:
            - AttributeName: to
              KeyType: HASH
        - IndexName: ${self:custom.dynamoDbTableFromIdx}
          KeySchema:
            - AttributeName: from
              KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: 'ttl'
        Enabled: true
      SSESpecification:
        SSEEnabled: true

Outputs:
  FileSharingTableName:
    Value:
      Ref: FileSharingTable